### ISSUE TITLE
scripts/inject race condition with browsersync

### ISSUE THREAD

**Issue by JackNorris** [Swiip/generator-gulp-angular#575]
Not sure if it's me doing something wrong or if this is indeed a bug. I'm quite new to gulp so it is entirely possible I am being stupid.

I have set up the generator in a typescript configuration, with all the default settings.

I'm having issues with browser-sync reloading too early when adding new typescript files into the application. Basically the browser reloads after the scripts are compiled but before they are injected into the .html.

Example.

1. run 'gulp serve' 
2. Create new .ts file in ./src/app
3. Browser reloads when the scripts task is run, browser reloads successfully.
4. Inject task runs and triggers browser reload. Browser does not reload because it is still mid-reload from the scripts task.
5. The loaded page does not include the newly injected .ts file. Performing a manual refresh of the browser corrects this.

I'm assuming this is not intended behaviour? Are there any workarounds?

**Comment by AleskiWeb** [comment]
Hey Jack, I'm getting the same thing actually. Any idea what we can do about it?

**Comment by zckrs** [comment]
Hi @JackNorris
What version of generator you use ? v0.11 or master ?
Can you paste jour `.yo-rc.json` ?

**Comment by JackNorris** [comment]
Hi @zckrs 

I'm using v0.11, my .yo-rc.json is below

http://pastebin.com/TNNGdcWr

**Comment by JackNorris** [comment]
Right so I had a little play with master, and it *appears* to be immune to the issue. The master version seems to compile and concat all TS/JS into a single file (index.module.js). Since everything is now in a single file there are no new files to be injected which of course means no race condition!

I suppose that is problem solved? I don't know if anyone else wants to quickly look over it and make sure I haven't missed anything obvious.

**Comment by zckrs** [comment]
Since lastest release on NPM I have rewrite lot of file. This issue is not present in master

**Comment by zckrs** [comment]
:tada: Just released v0.12.0 :tada:
Your issue should be fixed. I close but if you can retry your case with a new fresh install of generator you are welcome. Any feedback would be appreciated (positive comments too ^_^).

**Comment by AleskiWeb** [comment]
Sorry to reopen this but I am still having the issue.

When I edit the Index.html, it says its been injected, but the page simply doesnt reflect that. It's like it reloads -> injects new code instead of injects new code -> reloads.

So each time i make a change to the html, i have to press save, I get the messages top right about browsersync and THEN i have to press refresh manually to see them reflected.

Just did a fresh install of everything so I should be right up to date.
