### ISSUE TITLE
dist/scripts/vendor-######.js file is not compiling/minifying/uglifying correctly with out-of-the-box build

### ISSUE THREAD

**Issue by jahammo2** [Swiip/generator-gulp-angular#638]
##### Here are my options I choose after $ yo gulp-angular <filename>:
- 1.4.0 (angular)
- none (modules)
- 2.x (jquery)
- ngResource
- ngRoute
- BootStrap
- Angular UI (bootstrap)
- Sass (Node)
- CoffeeScript
- Jade

Once it's done building, and without making any changes whatsoever, I run
**$ gulp serve:dist**

and the build doesn't work. Specifically, the uglified version of code that ends up in dist/scripts/vendor-#####.js, which causes the whole build to not work.

Here is the error I'm getting in the console:
```Error: [$injector:unpr] Unknown provider: tProvider <- t
http://errors.angularjs.org/1.4.1/$injector/unpr?p0=tProvider%20%3C-%20t
    at http://localhost:3002/scripts/vendor-c7c85932a2.js:32:380
    at http://localhost:3002/scripts/vendor-c7c85932a2.js:32:19631
    at Object.r [as get] (http://localhost:3002/scripts/vendor-c7c85932a2.js:32:18801)
    at http://localhost:3002/scripts/vendor-c7c85932a2.js:32:19728
    at r (http://localhost:3002/scripts/vendor-c7c85932a2.js:32:18801)
    at Object.i [as invoke] (http://localhost:3002/scripts/vendor-c7c85932a2.js:32:19138)
    at f.instance (http://localhost:3002/scripts/vendor-c7c85932a2.js:33:9293)
    at g (http://localhost:3002/scripts/vendor-c7c85932a2.js:32:30984)
    at s (http://localhost:3002/scripts/vendor-c7c85932a2.js:32:27443)
    at s (http://localhost:3002/scripts/vendor-c7c85932a2.js:32:27466) <div ng-view="" class="ng-scope">(anonymous function) @ vendor-c7c85932a2.js:33```
![screen shot 2015-06-26 at 2 44 54 pm](https://cloud.githubusercontent.com/assets/9851764/8384858/00583800-1c12-11e5-91f0-85054bb862f9.png)


My guess is the problem resides in the CoffeeScript choice. Because if I choose ES6 (Babel...), I don't have this problem straight out-of-the-box.

I do not get this problem if I just run
**$ gulp serve**
or if I comment out
```.pipe($.uglify({ preserveComments: $.uglifySaveLicense })).on('error', conf.errorHandler('Uglify'))```
in gulp/build.js

**Comment by zckrs** [comment]
Nice description for issue. Thank you.
You are right. Coffescript and uglify are the problem.

If you comment the uglify pipe that should work. I suspect the `@ngInject` tag

We need investigate

**Comment by admorphit** [comment]
+1 this should be covered by tests

**Comment by wgorder** [comment]
+1

**Comment by wgorder** [comment]
Hmm closer, but while I can build the minified version now, I get a `Uncaught ReferenceError: describe is not defined` when doing a `gulp serve:dist` however `gulp serve` appears to still work.

**Comment by wgorder** [comment]
@zckrs  I figured it out resolved in https://github.com/Swiip/generator-gulp-angular/issues/657

**Comment by christophertrudel** [comment]
Same options as above except NO Jade, UI-Router or Bootstrap.

Applied the commits and still no luck. Any insight?

![screen shot 2015-09-05 at 5 11 16 pm](https://cloud.githubusercontent.com/assets/394759/9701673/34485728-53f1-11e5-8979-cab18d24af7a.png)
